config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # get 'home/index'
  get 'home/team'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # what follows is called a filter, describes where common content can
  # be used
  before_action :common_content, only: %i[index team]

  def common_content
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @hero_title = Faker::Job.title
    @hero_job = Faker::Company.bs.titleize
    @hero_saying = Faker::TvShows::DrWho.quote

    rnd_set = rand(1..2)
    @set = if rnd_set == 1
             'set1'
           else
             'set2'
           end

    bk_set = rand(1..2)
    @bg_set = if bk_set == 1
                'bg1'
              else
                'bg2'
              end

    @avatar = Faker::Avatar.image(slug: @hero_name, size: '300x300', format: 'png', set: @set, bgset: @bg_set)
  end

  def index; end

  def team; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'SUPERHERO NAME GENERATOR', root_path, class: 'navbar-brand text-primary' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id='navbarNav'>

    <ul class="navbar-nav">
      <li class="nav-item"> <%= link_to 'Create a Superhero', root_path, class: 'nav-link' %> </li>
      <li class="nav-item"><%= link_to 'Create a Superhero Team', home_team_path, class: 'nav-link' %></li>
    </ul>

  </div>
</nav>

app/views/home/index.html.erb
<div></div><div class='container-md mt-4'>
  <div class="card">
    <div class="card-header">
      <%= link_to 'Click here to generate a new superhero', root_path, class: 'card-link text-muted'%> 
    </div>
    <div class="card-body pt-4 pb-3">

      <div class="row">
        <div class="col-md-4">
        <img src="<%= @avatar %>"></img>
        </div>
        <div class="col-md-4">  
          <h5 class="card-title">
            Your Superhero Name: <br>
            <span class="text-danger"><%= @hero_name %></span>
          </h5>
          <h5 class="card-title">
            Your Super Power: <br>
            <span class="text-danger"><%= @hero_power %></span>
          </h5>
          <br>
          <h6 class="card-title">
            Your Favorite Saying: <br>
            <span class="font-italic text-primary"><small><%= @hero_saying %></small></span>
          </h6>
          <h6 class="card-title">
            Your Undercover Day Job: <br>
            <span class="text-primary"><%= @hero_title %></span>
          </h6>
          <h6 class="card-title">
            Your Corporate Superpower: <br>
            <span class="text-primary"><%= @hero_job %></span>
          </h6>
        </div>
        <div class="col-md-4">
        </div>
      </div>

      
    </div>
    <div class="card-footer">
      <%= link_to 'Create a Superhero Team', home_team_path, class: 'card-link text-muted' %>
    </div>
  </div>
</div>

app/views/home/team.html.erb
<div class='container-md mt-4'>
  <div class="card">
    <div class="card-header">
      <%= link_to 'Click here to generate a new superhero', root_path, class: 'card-link text-muted'%> 
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @name %></h5>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
    <div class="card-footer text-muted">
      <%= link_to 'Create a Superhero Team', home_team_path, class: 'card-link text-muted' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Superhero Name Generator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'home/navbar' %>


    <%= yield %>
<br>
    <p class='text-center'><br>Based on design by JohnFelder.org - All Rights Reserved<br>
    Robots lovingly delivered by robohash.org<br>
    Text delivered by faker-ruby</small></p>
  </body>
</html>